name: build-lambda-layer # https://gist.github.com/wyllie/1a2d32a3282f817e1f2bebea95ab4c38

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python Version'
        required: true
        type: number
        default: 3.10

env:
  layer_name: ToxicCommentLayer
  bucket_name: <your AWS S3 bucket name goes here>
  bucket_uri: <the uri for your S3 bucket - like s3://my_bucket_name>

permissions:
  id-token: write
  contents: read

jobs:
  build-lambda-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: happysad2/toxic_comment_challenge
          ref: main

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::0000000000000:role/GitHubActionsDeployRole
          role-session-name: GitHubActionsBuildLambdaLayer
          aws-region: ap-southeast-2

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Zip it all up and upload to S3
        run: |
          mkdir python

          pip install -r requirements/layer.txt -t python
          pip install . -t  python

          zip --quiet -r ${{ env.layer_name }} python

          aws s3 cp ${{ env.layer_name }} ${{ env.bucket_uri }}
          aws lambda publish-layer-version --layer-name ${{ env.layer_name }}  --content S3Bucket=${{ env.bucket_name }},S3Key=${{ env.layer_name }} --compatible-runtimes python${{ inputs.python_version }}
